{
  "status": "FAILURE",
  "createdAt": 1657311221549,
  "updatedAt": 1657311224245,
  "runtime": 2696,
  "error": {
    "reason": "missing revert data in call exception; Transaction reverted without a reason string",
    "code": "CALL_EXCEPTION",
    "data": "0x",
    "transaction": {
      "to": "0x62BB4fc73094c83B5e952C2180B23fA7054954c4",
      "data": "0x8e6d536a000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000",
      "accessList": null
    },
    "error": {
      "reason": "processing response error",
      "code": "SERVER_ERROR",
      "body": "{\"jsonrpc\":\"2.0\",\"id\":58,\"error\":{\"code\":-32000,\"message\":\"execution reverted\"}}",
      "error": {
        "code": -32000
      },
      "requestBody": "{\"method\":\"eth_call\",\"params\":[{\"to\":\"0x62bb4fc73094c83b5e952c2180b23fa7054954c4\",\"data\":\"0x8e6d536a000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000\"},\"latest\"],\"id\":58,\"jsonrpc\":\"2.0\"}",
      "requestMethod": "POST",
      "url": "https://opt-mainnet.g.alchemy.com/v2/YsYZIvlgzY2QbRhE4eQFumv_PQnhLBk-"
    }
  }
}